In [65]:
import pandas as pd
df = pd.read_csv(r'csv/casas-jurica-entrenamiento.csv', dtype="string")
df1 = pd.read_csv(r'csv/casas-jurica.csv', dtype="string")
df['precio'] = df['precio'].fillna('0')
df['precio'] = df['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','').replace('NM','')).astype(float)
df['mets'] = df['mets'].fillna('0')
df['mets'] = df['mets'].apply(lambda x: x.replace(' ','').replace('m²', '')).astype(float)
df1['precio'] = df1['precio'].fillna('0')
df1['precio'] = df1['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','').replace('NM','')).astype(float)
df1['mets'] = df1['mets'].fillna('0')
df1['mets'] = df1['mets'].apply(lambda x: x.replace(' ','').replace('m²', '')).astype(float)
from sklearn import linear_model

In [66]:
print('Size of the df: {} items'.format(df.count()['titulo']))

Size of the df: 458 items

In [67]:
print (df)

    web-scraper-order                              web-scraper-start-url  \
0    1620528210-16193  https://www.inmuebles24.com/casas-en-venta-en-...
1    1620528298-16374  https://www.inmuebles24.com/casas-en-venta-en-...
2    1620528210-16175  https://www.inmuebles24.com/casas-en-venta-en-...
3    1620528356-16489  https://www.inmuebles24.com/casas-en-venta-en-...
4    1620528348-16484  https://www.inmuebles24.com/casas-en-venta-en-...
..                ...                                                ...
453  1620506713-11711  https://www.lamudi.com.mx/queretaro-arteaga/qu...
454  1620507335-11774  https://www.lamudi.com.mx/queretaro-arteaga/qu...
455   1620503643-8878  https://www.lamudi.com.mx/queretaro-arteaga/qu...
456  1620508015-11847  https://www.lamudi.com.mx/queretaro-arteaga/qu...
457  1620507238-11764  https://www.lamudi.com.mx/queretaro-arteaga/qu...

                                                titulo      precio   habts  \
0    Residencia en Venta en Jurica con Alberca y Fr...  11350000.0  5 rec.
1    Casa Estilo Mexicano Contemporáneo en Una de L...  10990000.0  4 rec.
2    Jurica, Residencia en Venta en Privada con Vig...  13000000.0  3 rec.
3            Casa 3 Hab + Sala de Tv en Arco de Piedra   8150000.0  3 rec.
4    Espectacular! Arquitectura Moderna de 1 Planta...  25000000.0  5 rec.
..                                                 ...         ...     ...
453                     Casa de oportunidad en Jurica.   7094000.0       2
454  Jurica casa con excelente estado de conservaci...   3320000.0       2
455  Casa remodelada en Jurica de 3 dormitorios y 4...  13500000.0       4
456  Casa en Jurica con espacios muy funcionales y ...   3320000.0       2
457  Jurica Residencia con 5 recamaras todas con ba...  11350000.0       5

                     ban    mets
0    5

						baños   920.0
1    4

						baños  1000.0
2    4

						baños   510.0
3    3

						baños   302.0
4    5

						baños  1789.0
..                   ...     ...
453                    4   372.0
454                    3   235.0
455                    3   445.0
456                    3   235.0
457                    6   920.0

[458 rows x 7 columns]

In [124]:
metros = pd.DataFrame([df['mets']])

In [125]:
precios = pd.DataFrame([df['precio']])

In [126]:
print (metros)

        0       1      2      3       4       5      6       7       8    \
mets  920.0  1000.0  510.0  302.0  1789.0  2220.0  420.0  1000.0  1304.0

        9    ...    448     449    450    451    452    453    454    455  \
mets  525.0  ...  235.0  2220.0  350.0  780.0  266.0  372.0  235.0  445.0

        456    457
mets  235.0  920.0

[1 rows x 458 columns]

In [127]:
print (precios)

               0           1           2          3           4           5    \
precio  11350000.0  10990000.0  13000000.0  8150000.0  25000000.0  22000000.0

              6           7           8          9    ...        448  \
precio  8000000.0  10500000.0  12500000.0  6300000.0  ...  3320000.0

               449         450         451        452        453        454  \
precio  15000000.0  12500000.0  16500000.0  6700000.0  7094000.0  3320000.0

               455        456         457
precio  13500000.0  3320000.0  11350000.0

[1 rows x 458 columns]

In [128]:
model = linear_model.LinearRegression()

In [129]:
model.fit(metros,precios)

LinearRegression()

In [137]:
model.predict(pd.DataFrame([df['precio']]))

array([[11350000., 10990000., 13000000.,  8150000., 25000000., 22000000.,
         8000000., 10500000., 12500000.,  6300000.,  9500000., 11350019.,
        14000000., 13900000.,  6200000., 11500000., 21500000.,  8750000.,
        35000000.,  9500000., 13000000., 18950000.,  8500000.,  9800000.,
        13500081.,  8900000., 14500000.,  9500000., 15500000., 10500000.,
        21850000.,  8300000., 13500000., 21500000., 12500000.,  4750000.,
        13500000.,  6200000.,  4350000., 12000000., 17000000., 12800000.,
        10200000.,  3320000., 12000000.,  5100000., 13700000.,  7900000.,
         3894830., 15000000., 12000000., 19500000.,  3320081.,  6200000.,
        15000000.,  6800000., 16850000., 19750000.,  6400000.,  6200019.,
         8490000., 20000000.,  3000000., 19950000.,  8750000., 22000000.,
         8000000., 17999000.,  5300000.,   775000.,  6200019.,  5500000.,
        13200000.,  5800000., 25000000., 19750000., 15500000., 35000000.,
        10250000.,  4800000.,  8500000., 15000000., 10500000.,  4750000.,
         7990000.,  6200000.,  2180000.,  3750000., 12000000., 10500000.,
         8150000., 11000000.,  3894830., 18950000., 22000000.,  9400000.,
        10500000.,  9200000., 16500000.,  5950000.,  6850000.,  7000000.,
        18000000.,  9000000.,  3320007.,  6300000.,  3200000.,  6300000.,
        13500000.,  9450000., 11350000., 12000000.,  5390000.,  3170000.,
        15000000., 12800000.,  7900000.,  3320000.,  7800000.,  7300000.,
        19950000.,  5250000.,  8900000., 13500072., 11350081., 16850000.,
         2870000.,  4750000.,  9200000.,  8500000.,  7990000.,  9500000.,
         6300000., 36000000., 19950000., 22000000.,  6300000., 19950000.,
        13000000.,  6200000.,  4800000., 12000000., 10500000.,  3320000.,
        18000000., 13000000.,  6200000., 13000000., 13900000., 21250000.,
         6800000.,  7000000.,  3170000., 20000000., 11990000., 10800000.,
        19950000.,  7500000., 18950000., 10000000.,  1580000., 11950000.,
        12500000.,  8500000.,  8500000.,  4750000., 13000000.,  5950000.,
         6750000.,  5300000.,  5300000.,  5471000., 12500000., 16500000.,
        10000000., 10500000.,  8150000., 20000000., 10990000.,  2870000.,
         9500000.,  8600000.,  7300000., 11500000.,  7130000.,  9200000.,
         3320000.,  8600000., 20000000.,  3320019.,  8500000., 11350000.,
         4800000., 12000000., 27000000., 11349971., 10500000., 12500000.,
         2870000., 20000000.,  6500000.,  5700000., 16000000.,  6200000.,
        13500000., 11900000.,  3320000.,  5500000.,  9500000., 12200000.,
         5300000., 16500000., 10500000., 10250000., 12500000.,  7990000.,
        10900000., 10000000.,  7100000.,  7100000., 16500000., 10000000.,
        11900000., 13500000.,  4000000., 21850000.,  6900000.,  3000000.,
        16500000.,  5800000., 13000000., 11350000., 19000000.,  2870000.,
         7500000., 12990000.,  6200000.,  5309000.,  6300000.,  5309000.,
         6450000.,  7100000.,  7890000., 18000000., 12000000., 16500000.,
        12500000., 11350019., 11300000.,  8500000.,  6200081., 13900000.,
        12800000.,  9800000., 13000000.,  1837000.,  5700000.,  4750000.,
         4800000., 12500000.,  4490000.,  6900000.,  8750000.,  3320072.,
         6300000.,  6400000., 12000000.,  6800000.,  3320000.,  8500000.,
        13000000.,  7990000.,  7100000.,  9000000., 10900000., 12500000.,
        17500000., 11600000., 10000000., 13500072.,  8500000.,  7990000.,
         9500000.,  6200000.,  9500000.,  6500000., 17000000., 18990000.,
         7300000.,  2990000.,  7000000., 13500000., 16850000.,  7300000.,
        10000000., 11350000., 35000000.,  6300000., 18000000.,  7500000.,
         5500000.,  9800000.,  8800000.,  3320000.,  6200000., 17750000.,
         6800000.,  2990000., 11600000., 21250000., 13537637., 13500000.,
         6200000., 10500000., 20000000., 13750000., 15000000., 18850000.,
         9850000., 12000000.,  8500000.,  9990000.,  9800000., 19500000.,
        15500000.,  6200000., 35000000.,  6900000., 21500000.,  8469000.,
        13000000.,  9700000.,  6200002.,  8900000., 16000000., 17750000.,
        10500000.,  9500000.,  3320000., 12200000.,  6200000.,  7000000.,
        14500000.,  3550541., 13500000.,  3967550.,  3949000.,  5500000.,
         3320000.,  5700000., 14000000., 12990000.,  9400000., 13500000.,
        10000000.,  7400000., 10990000.,  2674558.,  5300000.,  5500000.,
        12900000., 11350081.,  6738000.,  6490000., 13500000.,  6200081.,
        15000000.,  7990000., 14500000., 14500000.,  9500000.,  5300000.,
         6200000., 16500000.,  7900000.,  9400000.,  6950000.,  4600000.,
        10500000.,  6800000., 12200000., 14500000.,  3320000.,  8500000.,
        13000000.,  8900000.,  7130000.,  3750000.,  6200000.,  3320000.,
         8500000., 11350000., 35000000.,  7300000.,  6500000., 11990000.,
         8500000., 16500000.,  4750000.,  3320000.,  2990000., 13000000.,
        12000000.,  6200000.,  7300000., 13500000.,  8000000.,  5300000.,
         6200000., 16500000., 11400000., 21500000., 16500000.,  6738000.,
        11350000.,  6200000., 16500000., 12000000., 14500000.,  6200000.,
        19980000.,  6200000., 11350000., 13500000., 16500000.,  7300000.,
        10700000., 12000000.,  2877133.,  7300000.,  9000000., 16500000.,
         4200000., 35000000., 11350000., 10500000.,  6200000.,  6199000.,
         6200000.,  7900000.,  6900000.,  7800000.,  7130000.,  7500000.,
         9100000.,  3320000.,  7300000.,  6800000.,  3320000., 15000000.,
        12500000., 16500000.,  6700000.,  7094000.,  3320000., 13500000.,
         3320000., 11350000.]])

In [106]:
print(df1)

    web-scraper-order                              web-scraper-start-url  \
0    1620528210-16193  https://www.inmuebles24.com/casas-en-venta-en-...
1    1620528298-16374  https://www.inmuebles24.com/casas-en-venta-en-...
2    1620528210-16175  https://www.inmuebles24.com/casas-en-venta-en-...
3    1620528356-16489  https://www.inmuebles24.com/casas-en-venta-en-...
4    1620528348-16484  https://www.inmuebles24.com/casas-en-venta-en-...
..                ...                                                ...
747  1620507308-11771  https://www.lamudi.com.mx/queretaro-arteaga/qu...
748  1620506699-11709  https://www.lamudi.com.mx/queretaro-arteaga/qu...
749   1620504373-9336  https://www.lamudi.com.mx/queretaro-arteaga/qu...
750  1620506219-11666  https://www.lamudi.com.mx/queretaro-arteaga/qu...
751  1620507089-11750  https://www.lamudi.com.mx/queretaro-arteaga/qu...

                                                titulo      precio   habts  \
0    Residencia en Venta en Jurica con Alberca y Fr...  11350000.0  5 rec.
1    Casa Estilo Mexicano Contemporáneo en Una de L...  10990000.0  4 rec.
2    Jurica, Residencia en Venta en Privada con Vig...  13000000.0  3 rec.
3            Casa 3 Hab + Sala de Tv en Arco de Piedra   8150000.0  3 rec.
4    Espectacular! Arquitectura Moderna de 1 Planta...  25000000.0  5 rec.
..                                                 ...         ...     ...
747  CASA EN VENTA EN PRIVADA EN JURICA CAMPESTRE Q...  16500000.0       6
748           Casa en venta Jurica 3 habitaciones JGCC   6200000.0       3
749          VENTA CASAS -  JURICA REGENCY - QUERETARO  21000000.0       7
750  Casa lujosa en Jurica de 5 dormitorios y 505 m...  16500000.0       6
751           Casa sola en Venta, en Jurica, Querétaro   6900000.0       3

                     ban    mets
0    5

						baños   920.0
1    4

						baños  1000.0
2    4

						baños   510.0
3    3

						baños   302.0
4    5

						baños  1789.0
..                   ...     ...
747                    4   510.0
748                  3.5   316.0
749                    7   925.0
750                    5   505.0
751                    6   470.0

[752 rows x 7 columns]

In [138]:
metros1 = pd.DataFrame([df1['mets']])
print(metros1)

        0       1      2      3       4       5      6       7       8    \
mets  920.0  1000.0  510.0  302.0  1789.0  2220.0  420.0  1000.0  1304.0

        9    ...    742    743    744    745    746    747    748    749  \
mets  525.0  ...  217.0  445.0  400.0  235.0  210.0  510.0  316.0  925.0

        750    751
mets  505.0  470.0

[1 rows x 752 columns]

In [139]:
precios1 = pd.DataFrame([df1['precio']])
print(precios1)

               0           1           2          3           4           5    \
precio  11350000.0  10990000.0  13000000.0  8150000.0  25000000.0  22000000.0

              6           7           8          9    ...        742  \
precio  8000000.0  10500000.0  12500000.0  6300000.0  ...  8500000.0

               743        744        745        746         747        748  \
precio  13500000.0  8500000.0  3320000.0  3320000.0  16500000.0  6200000.0

               749         750        751
precio  21000000.0  16500000.0  6900000.0

[1 rows x 752 columns]

In [140]:
model1 = linear_model.LinearRegression()

In [145]:
model1.fit(metros1,precios1)

LinearRegression()

In [147]:
model1.predict(pd.DataFrame([df1['mets']]))

array([[11350000., 10990000., 13000000.,  8150000., 25000000., 22000000.,
         8000000., 10500000., 12500000.,  6300000.,  9500000., 11350019.,
        14000000., 13900000.,  6200000., 11500000., 21500000.,  8750000.,
        35000000.,  9500000., 13000000., 18950000.,  8500000.,  9800000.,
        13500081.,  8900000., 14500000.,  9500000., 15500000., 10500000.,
        21850000.,  8300000., 13500000., 21500000., 12500000.,  4750000.,
        13500000.,  6200000.,  4350000., 12000000., 17000000., 12800000.,
        10200000.,  3320000., 12000000.,  5100000., 13700000.,  7900000.,
         3894830., 15000000., 12000000., 19500000.,  3320081.,  6200000.,
        15000000.,  6800000., 16850000., 19750000.,  6400000.,  6200019.,
         8490000., 20000000.,  3000000., 19950000.,  8750000., 22000000.,
         8000000., 17999000.,  5300000.,   775000.,  6200019.,  5500000.,
        13200000.,  5800000., 25000000., 19750000., 15500000., 35000000.,
        10250000.,  4800000.,  8500000., 15000000., 10500000.,  4750000.,
         7990000.,  6200000.,  2180000.,  3750000., 12000000., 10500000.,
         8150000., 11000000.,  3894830., 18950000., 22000000.,  9400000.,
        10500000.,  9200000., 16500000.,  5950000.,  6850000.,  7000000.,
        18000000.,  9000000.,  3320007.,  6300000.,  3200000.,  6300000.,
        13500000.,  9450000., 11350000., 12000000.,  5390000.,  3170000.,
        15000000., 12800000.,  7900000.,  3320000.,  7800000.,  7300000.,
        19950000.,  5250000.,  8900000., 13500072., 11350081., 16850000.,
         2870000.,  4750000.,  9200000.,  8500000.,  7990000.,  9500000.,
         6300000., 36000000., 19950000., 22000000.,  6300000., 19950000.,
        13000000.,  6200000.,  4800000., 12000000., 10500000.,  3320000.,
        18000000., 13000000.,  6200000., 13000000., 13900000., 21250000.,
         6800000.,  7000000.,  3170000., 20000000., 11990000., 10800000.,
        19950000.,  7500000., 18950000., 10000000.,  1580000., 11950000.,
        12500000.,  8500000.,  8500000.,  4750000., 13000000.,  5950000.,
         6750000.,  5300000.,  5300000.,  5471000., 12500000., 16500000.,
        10000000., 10500000.,  8150000., 20000000., 10990000.,  2870000.,
         9500000.,  8600000.,  7300000., 11500000.,  7130000.,  9200000.,
         3320000.,  8600000., 20000000.,  3320019.,  8500000., 11350000.,
         4800000., 12000000., 27000000., 11349971., 10500000., 12500000.,
         2870000., 20000000.,  6500000.,  5700000., 16000000.,  6200000.,
        13500000., 11900000.,  3320000.,  5500000.,  9500000., 12200000.,
         5300000., 16500000., 10500000., 10250000., 12500000.,  7990000.,
        10900000., 10000000.,  7100000.,  7100000., 16500000., 10000000.,
        11900000., 13500000.,  4000000., 21850000.,  6900000.,  3000000.,
        16500000.,  5800000., 13000000., 11350000., 19000000.,  2870000.,
         7500000., 12990000.,  6200000.,  5309000.,  6300000.,  5309000.,
         6450000.,  7100000.,  7890000., 18000000., 12000000., 16500000.,
        12500000., 11350019., 11300000.,  8500000.,  6200081., 13900000.,
        12800000.,  9800000., 13000000.,  1837000.,  5700000.,  4750000.,
         4800000., 12500000.,  4490000.,  6900000.,  8750000.,  3320072.,
         6300000.,  6400000., 12000000.,  6800000.,  3320000.,  8500000.,
        13000000.,  7990000.,  7100000.,  9000000., 10900000., 12500000.,
        17500000., 11600000., 10000000., 13500072.,  8500000.,  7990000.,
         9500000.,  6200000.,  9500000.,  6500000., 17000000., 18990000.,
         7300000.,  2990000.,  7000000., 13500000., 16850000.,  7300000.,
        10000000., 11350000., 35000000.,  6300000., 18000000.,  7500000.,
         5500000.,  9800000.,  8800000.,  3320000.,  6200000., 17750000.,
         6800000.,  2990000., 11600000., 21250000., 13537637., 13500000.,
         6200000., 10500000., 20000000., 13750000., 15000000., 18850000.,
         9850000., 12000000.,  8500000.,  9990000.,  9800000., 19500000.,
        15500000.,  6200000., 35000000.,  6900000., 21500000.,  8469000.,
        13000000.,  9700000.,  6200002.,  8900000., 16000000., 17750000.,
        10500000.,  9500000.,  3320000., 12200000.,  6200000.,  7000000.,
        14500000.,  3550541., 13500000.,  3967550.,  3949000.,  5500000.,
         3320000.,  5700000., 14000000., 12990000.,  9400000., 13500000.,
        10000000.,  7400000., 10990000.,  2674558.,  5300000.,  5500000.,
        12900000., 11350081.,  6738000.,  6490000., 13500000.,  6200081.,
        15000000.,  7990000., 14500000., 14500000.,  9500000.,  5300000.,
         6200000., 16500000.,  7900000.,  9400000.,  6950000.,  4600000.,
        10500000.,  6800000., 12200000., 14500000.,  3320000.,  8500000.,
        13000000.,  8900000.,  7130000.,  3750000.,  6200000.,  3320000.,
         8500000., 11350000., 35000000.,  7300000.,  6500000., 11990000.,
         8500000., 16500000.,  4750000.,  3320000.,  2990000., 13000000.,
        12000000.,  6200000.,  7300000., 13500000.,  8000000.,  5300000.,
         6200000., 16500000., 11400000., 21500000., 16500000.,  6738000.,
        11350000.,  6200000., 16500000., 12000000., 14500000.,  6200000.,
        19980000.,  6200000., 11350000., 13500000., 16500000.,  7300000.,
        10700000., 12000000.,  2877133.,  7300000.,  9000000., 16500000.,
         4200000., 35000000., 11350000., 10500000.,  6200000.,  6199000.,
         6200000.,  7900000.,  6900000.,  7800000.,  7130000.,  7500000.,
         9100000.,  3320000.,  7300000.,  6800000.,  3320000., 15000000.,
        12500000., 16500000.,  6700000.,  7094000.,  3320000., 13500000.,
         3320000., 11350000., 16500000.,  4800000., 11950000.,  7000000.,
        16500000.,  8300000.,  3320000.,  6200000.,  3320000., 11350000.,
         6400000., 11350000., 10990000., 16500000., 16500000., 13500000.,
         7094000., 11350000., 10800000.,  7890000.,  9980000., 12750000.,
        16500000., 11350000.,  6200000., 15000000.,  3320000., 13500000.,
        17000000., 13500000., 11350000., 27000000., 11800000., 19950000.,
         7100000.,  6200000.,  4750000., 21500000.,  6200000., 12200000.,
        11500000., 23000000., 20000000., 11000000.,  3320000., 11350000.,
         7900000.,  8490000.,  5300000., 11300000., 16500000., 18950000.,
         6738000.,  8750000., 21850000.,  6200000., 12000000.,  8800000.,
        12900000., 11350000., 16900000., 21250000., 16500000., 13000000.,
        14000000.,  7300000., 10000000.,  4250000.,  2870000., 13000000.,
         3320000.,  3320000., 13500000., 16500000., 13500000., 13500000.,
        17500000., 16500000.,  3320000.,  6200000.,  8500000.,  3894830.,
        11350000., 13000000., 16500000., 16500000.,  3170000.,  7500000.,
         7350000.,  8500000.,  3000000.,  8600000., 16500000., 15500000.,
         2180000.,  3320000., 12800000., 13500000., 21500000.,  5500000.,
        12500000., 10000000., 13000000., 12500000., 11350000., 16500000.,
         5300000.,  6200000.,  3320000., 16500000., 36000000.,  9800000.,
        11350000.,  5250000.,  7000000.,  3894830., 16500000.,  2100000.,
        11350000., 13500000., 16500000.,  3320000.,  3320000., 23000000.,
         7350000., 13500000., 11350000., 21000000., 16500000., 12900000.,
        14000000.,  4350000., 15000000.,  6500000., 13500000.,  8300000.,
        22000000., 12500000., 16500000., 16500000., 16500000., 16500000.,
        16500000.,  8500000.,  3200000.,  6300000., 16500000.,  3320000.,
         3320000.,  6200000.,  8500000.,  8500000., 11350000.,  5800000.,
         9500000.,  5850000.,  3320000., 11350000., 12500000., 11350000.,
         7450000.,  3320000.,  3320000., 13500000., 11350000., 21500000.,
         5950000.,  9000000., 19950000., 16500000., 11500000.,  7900000.,
         7000000.,  2253500., 16500000., 15000000.,  3320000., 11000000.,
         3320000.,  3320000.,  9000000.,  4500000., 14250000.,  7500000.,
         3900000., 29000000., 16500000., 16500000.,  4950000., 12200000.,
        11900000.,  6200007.,  5309000.,  8500000.,  5600000.,  8740000.,
         6200000.,  5990000.,  3347948., 11350000.,  6200000.,  6500000.,
         3320000.,  8500000., 18850000., 16500000.,  6050000., 13500000.,
         3320000.,  3320000.,  3320000., 16500000.,  9000000., 21500000.,
        13500000.,  3320000.,  7500000.,  3320000.,  5300000., 13500000.,
        11350000.,  9500000.,  6200000., 11300000., 16500000.,  6200000.,
         9700000., 19000000., 12000000., 11350000.,  3320000., 13500000.,
         6200000.,  8900000., 16500000.,  6200000., 13500000.,  2253500.,
        13500000.,  6200000.,  6200000.,  6200000.,  6200000.,  6200000.,
        11350000.,  6200000., 11350000.,  4776510., 11350000.,  3320000.,
        11350000., 13500000.,  1125000., 16500000., 10500000., 11500000.,
         4980000.,  5300000., 16500000.,  3320000., 11000000., 19000000.,
         6200000., 12500000.,  7500000., 11000000., 13500000., 10190306.,
         6200000., 16000000., 16500000., 13000000., 11350000., 11350000.,
         4950000., 10900000.,  8500000.,  6200000., 11360001.,  8500000.,
        12500000., 11350000., 16500000., 10000000.,  8500000., 13500000.,
         8500000.,  3320000.,  3320000., 16500000.,  6200000., 21000000.,
        16500000.,  6900000.]])